---
- name: Verificar Docker Compose
  ansible.builtin.command:
    cmd: docker compose version
    chdir: "{{ project_dir }}"
  register: compose_version
  changed_when: false

- name: Exibir versão do Docker Compose
  ansible.builtin.debug:
    msg: "{{ compose_version.stdout }}"

- name: Fazer build da imagem do HTTP Server
  ansible.builtin.command:
    cmd: docker compose build http-server-projeto-korp
    chdir: "{{ project_dir }}"

- name: Iniciar stack com Docker Compose
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ project_dir }}"